package com.example.smartassistant.consumer.service.admin;

import com.example.smartassistant.common.db.DatabaseDialect;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;

class AdminServiceIdentityTest {

    private JdbcTemplate jdbc;
    private AdminService service;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:admin_identity_" + System.nanoTime() +
                ";DB_CLOSE_DELAY=-1;MODE=PostgreSQL");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE routing_call_log (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, " +
                "session_id VARCHAR(100), user_input VARCHAR(500), routed_agent VARCHAR(100), " +
                "response_summary VARCHAR(500), status VARCHAR(20), error_message VARCHAR(500), " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE conversation_feedback (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id VARCHAR(100), " +
                "user_id BIGINT, rating INT, feedback_text VARCHAR(500), agent_name VARCHAR(100), " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.update("INSERT INTO routing_call_log " +
                        "(user_id, session_id, user_input, routed_agent, response_summary, status) " +
                        "VALUES (?, ?, ?, ?, ?, ?)",
                42L, "session-42", "mine", "general", "answer", "SUCCESS");
        jdbc.update("INSERT INTO routing_call_log " +
                        "(user_id, session_id, user_input, routed_agent, response_summary, status) " +
                        "VALUES (?, ?, ?, ?, ?, ?)",
                99L, "session-99", "other", "general", "secret", "SUCCESS");
        service = new AdminService(jdbc, mock(DatabaseDialect.class));
    }

    @Test
    void normalUserCanOnlyReadOwnSessions() {
        List<Map<String, Object>> sessions = service.getSessions(42L, false);

        assertEquals(1, sessions.size());
        assertEquals("session-42", sessions.get(0).get("id"));
        assertFalse(service.getSessionDetail("session-99", 42L, false).containsKey("messages"));
        assertTrue(service.getSessionDetail("session-42", 42L, false).containsKey("messages"));
    }

    @Test
    void normalUserCannotDeleteOrCloseAnotherUsersSession() {
        assertFalse(service.deleteSession("session-99", 42L, false));
        assertFalse(service.closeSession("session-99", 42L, false));
        assertEquals(1L, jdbc.queryForObject(
                "SELECT COUNT(*) FROM routing_call_log WHERE session_id = 'session-99'", Long.class));
    }
}
