package com.example.smartassistant.consumer.service.dispatch;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.test.util.ReflectionTestUtils;
import java.util.*;
import java.util.concurrent.*;
import static org.junit.jupiter.api.Assertions.*;

/** Opt-in; cleans only exact keys generated by this test, never a production key glob. */
@EnabledIfEnvironmentVariable(named = "CHAT_DISPATCH_TEST_REDIS_PORT", matches = "\\d+")
class ChatDispatchRedisIntegrationTest {
    private LettuceConnectionFactory connection;
    private StringRedisTemplate redis;
    private ChatDispatchStore store;
    private final Set<String> keys = new HashSet<>();
    private long userId;
    @BeforeEach void setup() {
        var config = new org.springframework.data.redis.connection.RedisStandaloneConfiguration(
                System.getenv().getOrDefault("CHAT_DISPATCH_TEST_REDIS_HOST", "127.0.0.1"),
                Integer.parseInt(System.getenv("CHAT_DISPATCH_TEST_REDIS_PORT")));
        String password = System.getenv("CHAT_DISPATCH_TEST_REDIS_PASSWORD");
        if (password != null && !password.isBlank()) config.setPassword(password);
        connection = new LettuceConnectionFactory(config);
        connection.afterPropertiesSet(); connection.start();
        redis = new StringRedisTemplate(connection); redis.afterPropertiesSet();
        store = new ChatDispatchStore(redis, new ObjectMapper());
        userId = ThreadLocalRandom.current().nextLong(1_000_000_000L, Long.MAX_VALUE);
    }
    @AfterEach void cleanup() {
        if (redis != null && !keys.isEmpty()) redis.delete(keys);
        if (connection != null) connection.destroy();
    }
    private ChatDispatchCommand command(long owner, long expiry) {
        var command = new ChatDispatchCommand(owner, "test-session", "test-" + UUID.randomUUID(), "查询测试订单", false, 0, expiry);
        keys.add(ReflectionTestUtils.invokeMethod(store, "key", command.requestId()));
        keys.add("chat:dispatch:v1:{dispatch}:user:" + owner);
        return command;
    }
    @Test void concurrentDeliveriesProduceOneExecutionOwnerAndDurableResult() throws Exception {
        var command = command(userId, System.currentTimeMillis() + 30000);
        store.reserve(command);
        try (var executor = Executors.newFixedThreadPool(8)) {
            var calls = new ArrayList<Callable<String>>();
            for (int i = 0; i < 20; i++) calls.add(() -> store.start(command, System.currentTimeMillis()));
            long acquired = 0;
            for (var result : executor.invokeAll(calls)) if ("ACQUIRED".equals(result.get())) acquired++;
            assertEquals(1, acquired);
        }
        assertTrue(store.finish(command, "RUNNING", "COMPLETED", Map.of("result", "完成")));
        assertFalse(store.finish(command, "RUNNING", "COMPLETED", Map.of("result", "重复")));
        assertEquals("完成", store.result(command).get("result"));
        assertEquals("COMPLETED", store.start(command, System.currentTimeMillis()));
    }
    @Test void accountAdmissionAndRequestBindingPreventCrossSessionOrCrossUserReuse() {
        var command = command(userId, System.currentTimeMillis() + 30000);
        store.reserve(command);
        assertThrows(IllegalStateException.class, () -> store.reserve(command(userId, System.currentTimeMillis() + 30000)));
        assertThrows(IllegalArgumentException.class, () -> store.reserve(new ChatDispatchCommand(userId,
                "other-session", command.requestId(), command.question(), false, 0, command.expiresAt())));
        assertThrows(SecurityException.class, () -> store.ownedCommand(userId - 1, command.requestId()));
        assertTrue(store.finish(command, "QUEUED", "CANCELLED", PriorityRoutingDispatcher.cancelled()));
        assertDoesNotThrow(() -> store.reserve(command(userId, System.currentTimeMillis() + 30000)));
        assertEquals("CANCELLED", store.start(command, System.currentTimeMillis()));
    }
    @Test void expiredQueueCanBeReclaimedButUncertainExecutionCannot() {
        var old = command(userId, 1);
        store.reserve(old);
        var next = command(userId, System.currentTimeMillis() + 30000);
        store.reserve(next);
        assertEquals("EXPIRED", store.status(old));
        assertEquals("ACQUIRED", store.start(next, System.currentTimeMillis()));
        assertTrue(store.finish(next, "RUNNING", "UNCERTAIN", PriorityRoutingDispatcher.failure("UNKNOWN", "待核查")));
        assertThrows(IllegalStateException.class, () -> store.reserve(command(userId, System.currentTimeMillis() + 30000)));
    }
}
