/** Display-only alias. Never use this value for authentication or data ownership. */
export function getUserDisplayName(username?: string | null, fallback = '用户'): string {
  if (!username?.trim()) return fallback;
  // Match the exact account format generated by createDemoAccount, not all demo_* users.
  return /^demo_[0-9a-f]{32}$/i.test(username) ? '演示用户' : username;
}
